### ISSUE TITLE
Injecting using mixins?

### ISSUE THREAD

**Issue by anlutro** [alecthomas/injector#58]
I've got an application where classes can inherit from multiple mixins, which have at least one dependency and may also have various helper methods. Using the `@inject` decorator on the class, this seemed rather straight forward:

```
from injector import Injector, inject

class SomeThing: pass
class OtherThing: pass

@inject(thing=SomeThing)
class ThingMixin: pass

@inject(other=OtherThing)
class OtherThingMixin: pass

class UserClass(ThingMixin, OtherThingMixin):
	def mymethod(self):
		print(self.thing)
		print(self.other)
```

This obviously doesn't work in recent versions where `@inject` on classes has been removed. It doesn't work in 0.10 either: `AttributeError: 'UserClass' object has no attribute 'other'`

Is there another way to allow this type of design without forcing the author of `UserClass` to declare every dependency in the constructor?

**Comment by anlutro** [comment]
Updated the description a bit since I misremembered. This is not a 0.11-specific issue.

**Comment by alecthomas** [comment]
> Is there another way to allow this type of design without forcing the author of UserClass to declare every dependency in the constructor?

Not really, no; you'll need to use constructor injection. Field injection made it difficult to use classes outside of the injector, among other things.

```python
from injector import Injector, inject

class SomeThing: pass
class OtherThing: pass


class ThingMixin:
  @inject(thing=SomeThing)
  def __init__(self, thing):
    self.thing = thing

class OtherThingMixin:
  @inject(other=OtherThing)
  def __init__(self, other):
    self.other = other

class UserClass(ThingMixin, OtherThingMixin):
  @inject(thing=SomeThing, other=OtherThing)
  def __init__(self, thing, other):
    ThingMixin.__init__(self, thing)
    OtherThingMixin.__init__(self, other)

  def mymethod(self):
    print(self.thing)
    print(self.other)
```
