### ISSUE TITLE
Compatibility with python 3.5.3

### ISSUE THREAD

**Issue by JGiard** [alecthomas/injector#135]
Hi,
There is a compatibility issue with python 3.5.3.
When I try to inject classes with no `__init__` function I get the following error :
`AttributeError: 'method-wrapper' object has no attribute '__func__'`

I traced it back to calling
```python
typing.get_type_hints(object.__init__)
```

It looks like the fix : https://github.com/python/typing/pull/368
was release with python 3.5.4, since then it is hardcoded to return an empty dict.

I understand if you would not want to add a workaround for an old python version, then the readme should be updated to specify the minimum version.
`Injector works with CPython 3.5+ and PyPy 3 implementing Python 3.5+.`

**Comment by jstasiak** [comment]
Hi, for full clarity: can you provide a stacktrace?

**Comment by JGiard** [comment]
Yes of course, here is a code fragment that works on python:3.5.4 docker image but not on python:3.5.3

```python
>>> from injector import Injector
>>> class Foo:
...     pass
... 
>>> Injector().get(Foo)
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/injector/__init__.py", line 938, in create_object
    self.call_with_injection(init, self_=instance, kwargs=additional_kwargs)
  File "/usr/local/lib/python3.5/site-packages/injector/__init__.py", line 958, in call_with_injection
    bindings = get_bindings(callable)
  File "/usr/local/lib/python3.5/site-packages/injector/__init__.py", line 1099, in get_bindings
    type_hints = get_type_hints(callable, include_extras=True)
  File "/usr/local/lib/python3.5/site-packages/injector/__init__.py", line 62, in get_type_hints
    return _get_type_hints(obj, globalns, localns)
  File "/usr/local/lib/python3.5/typing.py", line 1419, in get_type_hints
    'or function.'.format(obj))
TypeError: <slot wrapper '__init__' of 'object' objects> is not a module, class, method, or function.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/site-packages/injector/__init__.py", line 915, in get
    result = scope_instance.get(interface, binding.provider).get(self)
  File "/usr/local/lib/python3.5/site-packages/injector/__init__.py", line 276, in get
    return injector.create_object(self._cls)
  File "/usr/local/lib/python3.5/site-packages/injector/__init__.py", line 940, in create_object
    reraise(e, CallError(instance, instance.__init__.__func__, (), additional_kwargs, e, self._stack))
AttributeError: 'method-wrapper' object has no attribute '__func__'
```

**Comment by jstasiak** [comment]
Cheers. If you manually replace

```python
            self.call_with_injection(init, self_=instance, kwargs=additional_kwargs)
```

with 

```python
            if init is not object.__init__:
                self.call_with_injection(init, self_=instance, kwargs=additional_kwargs)
```

In the Injector source code will things work ok?

**Comment by JGiard** [comment]
Yes, it seems to work fine, both on the example and my real test :)

**Comment by jstasiak** [comment]
I just released version 0.18.3 with the fix.
